site_name: JSTOR Prison Education Documentation
use_directory_urls: false 

nav: 
- Home: index.md
- About: about.md
- Classroom Exercises: activities.md
- Students: students.md

extra_css:
  - css/labs.css